##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: 20th Century Postcards and Tourism
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: One Horse and Some Other Postcards
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: How did ordinary Americans in the first half of the twentieth century experience travel? What did they want to share with their friends and relatives about the places they had seen? We invite you to explore these questions through a collection of 31 postcards, ranging from 1905 to 1954. Some were sent from tourist destinations like Paris and Havana, others from obscure towns like Greenock, Scotland, or forgotten resorts like Saltair, Utah. Each postcard is a window into the sender’s life, a story in miniature. Read about air raids over Paris at the end of World War I, the experience of seeing Niagara Falls for the first time, and dating in small-town Washington. Whether it’s the text crammed onto the back, or the image on the front, these little postcards reflect the careful choices senders made about what to communicate to their loved ones, hundreds and sometimes thousands of miles away. 
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: postcards, history, twentieth century
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Team!

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: horsedata
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "207A Postcard Project"
organization-link: https://ampl.clair.ucsb.edu/hist-207a
organization-logo-banner: https://www.history.ucsb.edu/wp-content/uploads/UC-Santa-Barbara-History-White-RGB.png
organization-logo-nav: https://www.history.ucsb.edu/wp-content/uploads/UC-Santa-Barbara-History-White-RGB.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
